name: Main CI workflow

on: [push]

jobs:
  run-ci:
    name: Run CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: yarn type-check

      - name: Check linting
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build
