name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
